development:
  adapter: postgresql
  encoding: unicode
  database: budget
  pool: 5
  username: <%= ENV['USER'] %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: budget_test
  pool: 5
  username: <%= ENV['USER'] %>
  password:
